version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static/data:/app/static/data  # Persistencia de la base de datos
    environment:
      - FLASK_ENV=production
    restart: always
